//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanApplicant
    {
        public int loanId { get; set; }
        public string loanType { get; set; }
        public string loanAmountRequired { get; set; }
        public string applicantName { get; set; }
        public string applicantAddress { get; set; }
        public string applicantMobile { get; set; }
        public string applicantEmail { get; set; }
        public string applicantAadhaar { get; set; }
        public string applicantPan { get; set; }
        public string applicantSalary { get; set; }
        public string LoanRepaymentMethod { get; set; }
        public string LoanRepaymentMonths { get; set; }
        public string TimestampofLoan { get; set; }
        public int documentId { get; set; }
    
        public virtual Document Document { get; set; }
    }
}
